package pacoteFrames;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import pacoteBD.AcessoBD;
import pacoteclasse.Livro;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Larissa
 */
public class FrameCadastroLivro extends javax.swing.JFrame {
    Livro livro = new Livro();
    AcessoBD aBD = new AcessoBD();
    /**
     * Creates new form Biblioteca1
     */
    public FrameCadastroLivro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelBemVindo = new javax.swing.JPanel();
        lbBemvindo = new javax.swing.JLabel();
        painelCadastroLivro = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        tfTitulo = new javax.swing.JTextField();
        lbAutor = new javax.swing.JLabel();
        tfAutor = new javax.swing.JTextField();
        lbAno = new javax.swing.JLabel();
        lbIsbn = new javax.swing.JLabel();
        tfIsbn = new javax.swing.JTextField();
        lbGenero = new javax.swing.JLabel();
        cbGenero = new javax.swing.JComboBox<>();
        lbPaginas = new javax.swing.JLabel();
        lbEditora = new javax.swing.JLabel();
        tfEditora = new javax.swing.JTextField();
        tfAno = new javax.swing.JFormattedTextField();
        lbSnoopy2 = new javax.swing.JLabel();
        painelBotoes = new javax.swing.JPanel();
        btSalvar = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btBuscar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        btVoltar = new javax.swing.JButton();
        tfPaginas = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 221, 207));
        setForeground(new java.awt.Color(255, 221, 207));

        painelBemVindo.setBackground(new java.awt.Color(255, 255, 204));

        lbBemvindo.setBackground(new java.awt.Color(255, 221, 207));
        lbBemvindo.setForeground(new java.awt.Color(102, 0, 0));
        lbBemvindo.setText("Bem vindo ao cadastro de livros! Para continuar insira os seguintes dados:");

        painelCadastroLivro.setBackground(new java.awt.Color(255, 255, 204));

        lbTitulo.setBackground(new java.awt.Color(255, 221, 207));
        lbTitulo.setForeground(new java.awt.Color(51, 0, 0));
        lbTitulo.setText("Título:");

        tfTitulo.setForeground(new java.awt.Color(51, 0, 0));

        lbAutor.setBackground(new java.awt.Color(255, 221, 207));
        lbAutor.setForeground(new java.awt.Color(51, 0, 0));
        lbAutor.setText("Autor:");

        tfAutor.setForeground(new java.awt.Color(51, 0, 0));

        lbAno.setBackground(new java.awt.Color(255, 221, 207));
        lbAno.setForeground(new java.awt.Color(51, 0, 0));
        lbAno.setText("Ano:");

        lbIsbn.setBackground(new java.awt.Color(255, 221, 207));
        lbIsbn.setForeground(new java.awt.Color(51, 0, 0));
        lbIsbn.setText("ISBN:");

        tfIsbn.setForeground(new java.awt.Color(51, 0, 0));

        lbGenero.setBackground(new java.awt.Color(255, 221, 207));
        lbGenero.setForeground(new java.awt.Color(51, 0, 0));
        lbGenero.setText("Gênero:");

        cbGenero.setBackground(new java.awt.Color(255, 255, 204));
        cbGenero.setForeground(new java.awt.Color(51, 0, 0));
        cbGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tecnologia", "Romance", "Drama", " " }));

        lbPaginas.setBackground(new java.awt.Color(255, 221, 207));
        lbPaginas.setForeground(new java.awt.Color(51, 0, 0));
        lbPaginas.setText("Nº de páginas:");

        lbEditora.setBackground(new java.awt.Color(255, 221, 207));
        lbEditora.setForeground(new java.awt.Color(51, 0, 0));
        lbEditora.setText("Editora:");

        tfEditora.setForeground(new java.awt.Color(51, 0, 0));

        painelBotoes.setBackground(new java.awt.Color(255, 255, 204));

        btSalvar.setBackground(new java.awt.Color(255, 255, 153));
        btSalvar.setForeground(new java.awt.Color(102, 0, 0));
        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btAlterar.setBackground(new java.awt.Color(255, 255, 153));
        btAlterar.setForeground(new java.awt.Color(102, 0, 0));
        btAlterar.setText("Alterar");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        btExcluir.setBackground(new java.awt.Color(255, 255, 153));
        btExcluir.setForeground(new java.awt.Color(102, 0, 0));
        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btBuscar.setBackground(new java.awt.Color(255, 255, 153));
        btBuscar.setForeground(new java.awt.Color(102, 0, 0));
        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        btLimpar.setBackground(new java.awt.Color(253, 253, 212));
        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btSair.setBackground(new java.awt.Color(253, 253, 212));
        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        btVoltar.setBackground(new java.awt.Color(255, 153, 102));
        btVoltar.setForeground(new java.awt.Color(102, 51, 0));
        btVoltar.setText("Voltar");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelBotoesLayout = new javax.swing.GroupLayout(painelBotoes);
        painelBotoes.setLayout(painelBotoesLayout);
        painelBotoesLayout.setHorizontalGroup(
            painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btBuscar)
                .addGap(34, 34, 34)
                .addComponent(btLimpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSair)
                .addGap(27, 27, 27)
                .addComponent(btVoltar)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        painelBotoesLayout.setVerticalGroup(
            painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBotoesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btSair)
                        .addComponent(btLimpar)
                        .addComponent(btVoltar))
                    .addGroup(painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btSalvar)
                        .addComponent(btAlterar)
                        .addComponent(btExcluir)
                        .addComponent(btBuscar)))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout painelCadastroLivroLayout = new javax.swing.GroupLayout(painelCadastroLivro);
        painelCadastroLivro.setLayout(painelCadastroLivroLayout);
        painelCadastroLivroLayout.setHorizontalGroup(
            painelCadastroLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCadastroLivroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelCadastroLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelCadastroLivroLayout.createSequentialGroup()
                        .addComponent(lbAno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfAno, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbIsbn)
                        .addGap(8, 8, 8)
                        .addComponent(tfIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbGenero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelCadastroLivroLayout.createSequentialGroup()
                        .addGroup(painelCadastroLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(painelCadastroLivroLayout.createSequentialGroup()
                                .addComponent(lbTitulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbPaginas)
                                .addGap(2, 2, 2)
                                .addComponent(tfPaginas))
                            .addGroup(painelCadastroLivroLayout.createSequentialGroup()
                                .addComponent(lbAutor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbEditora)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(lbSnoopy2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(painelBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        painelCadastroLivroLayout.setVerticalGroup(
            painelCadastroLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCadastroLivroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelCadastroLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(painelCadastroLivroLayout.createSequentialGroup()
                        .addGroup(painelCadastroLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTitulo)
                            .addComponent(tfTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbPaginas)
                            .addComponent(tfPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(painelCadastroLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbAutor)
                            .addGroup(painelCadastroLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tfAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbEditora)
                                .addComponent(tfEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(5, 5, 5))
                    .addComponent(lbSnoopy2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelCadastroLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAno)
                    .addComponent(tfIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbIsbn)
                    .addComponent(lbGenero)
                    .addComponent(cbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(painelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );

        javax.swing.GroupLayout painelBemVindoLayout = new javax.swing.GroupLayout(painelBemVindo);
        painelBemVindo.setLayout(painelBemVindoLayout);
        painelBemVindoLayout.setHorizontalGroup(
            painelBemVindoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBemVindoLayout.createSequentialGroup()
                .addComponent(painelCadastroLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(painelBemVindoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lbBemvindo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelBemVindoLayout.setVerticalGroup(
            painelBemVindoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBemVindoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbBemvindo)
                .addGap(27, 27, 27)
                .addComponent(painelCadastroLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelBemVindo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelBemVindo, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        FrameCadastroLivro.this.dispose();
        FrameInicial inicial = new FrameInicial();
        inicial.setVisible(true);
    }//GEN-LAST:event_btVoltarActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btSairActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        tfTitulo.setText("");
        tfAutor.setText("");
        tfPaginas.setText("");
        tfEditora.setText("");
        tfAno.setText("");
        tfIsbn.setText("");
        cbGenero.setSelectedIndex(0);
    }//GEN-LAST:event_btLimparActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
              
         ResultSet rs;
         int numLinhas1 = 0;
         String isbn;
              
         
         isbn = tfIsbn.getText();
         
         
         try{
         rs = aBD.buscarLivroIsbn(isbn);
         
         while (rs.next()){
                
                tfTitulo.setText(rs.getString("TITULO"));
                tfPaginas.setText(rs.getString("PAGINAS"));
                tfAutor.setText(rs.getString("AUTOR"));
                tfAno.setText(rs.getString("ANO"));
                tfIsbn.setText(rs.getString("ISBN"));
                cbGenero.setSelectedItem(rs.getString("GENERO"));
                tfEditora.setText(rs.getString("EDITORA"));
                
         numLinhas1 ++;   
         }
         
         }catch (SQLException ex){
             Logger.getLogger(FrameCadastroLivro.class.getName()).log(Level.SEVERE, null, ex);
                 }

    }//GEN-LAST:event_btBuscarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
       
         String isbnBiblioteca;
        
        
        isbnBiblioteca = tfIsbn.getText();  
                  
        
        try {
            aBD.excluirLivroIsbn(isbnBiblioteca);
            
        } catch (SQLException ex) {
            Logger.getLogger(FrameCadastroLivro.class.getName()).log(Level.SEVERE, null, ex);
    }    
         LimparCampos();
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        livro.setTitulo(tfTitulo.getText());
        livro.setAutor(tfAutor.getText());
        livro.setPaginas(tfPaginas.getText());
        livro.setEditora(tfEditora.getText());
        livro.setAno(tfPaginas.getText());
        livro.setIsbn(tfIsbn.getText());
        livro.setGenero((String) cbGenero.getSelectedItem());
        btLimparActionPerformed(null);

        try {
            aBD.inserirNovoLivro(livro);
        } catch (SQLException ex) {
            Logger.getLogger(FrameCadastroLivro.class.getName()).log(Level.SEVERE, null, ex);
        }
        LimparCampos();
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
         String isbnBiblioteca;
        
        Biblioteca biblioteca = new Biblioteca();
        
        isbnBiblioteca = tfIsbn.getText();  
        
               biblioteca = new Biblioteca(
               tfTitulo.getText(),
               tfPaginas.getText(),
               tfAutor.getText(),
               tfAno.getText(),
               tfIsbn.getText(),
               (String)cbGenero.getSelectedItem(),
               tfEditora.getText());
                              
        
        try {
            aBD.alterarLivroIsbn(isbnBiblioteca, biblioteca);
            
        } catch (SQLException ex) {
            Logger.getLogger(FrameCadastroLivro.class.getName()).log(Level.SEVERE, null, ex);
        
    }   
    }//GEN-LAST:event_btAlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FrameCadastroLivro().setVisible(true);
        });
    }
    public void LimparCampos(){
        tfTitulo.setText("");
        tfAutor.setText("");
        tfPaginas.setText("");
        tfEditora.setText("");
        tfAno.setText("");
        tfIsbn.setText("");
        cbGenero.setSelectedIndex(0);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSair;
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton btVoltar;
    private javax.swing.JComboBox<String> cbGenero;
    private javax.swing.JLabel lbAno;
    private javax.swing.JLabel lbAutor;
    private javax.swing.JLabel lbBemvindo;
    private javax.swing.JLabel lbEditora;
    private javax.swing.JLabel lbGenero;
    private javax.swing.JLabel lbIsbn;
    private javax.swing.JLabel lbPaginas;
    private javax.swing.JLabel lbSnoopy2;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JPanel painelBemVindo;
    private javax.swing.JPanel painelBotoes;
    private javax.swing.JPanel painelCadastroLivro;
    private javax.swing.JFormattedTextField tfAno;
    private javax.swing.JTextField tfAutor;
    private javax.swing.JTextField tfEditora;
    private javax.swing.JTextField tfIsbn;
    private javax.swing.JTextField tfPaginas;
    private javax.swing.JTextField tfTitulo;
    // End of variables declaration//GEN-END:variables
}
