package pacoteFrames;


import pacoteFrames.FrameCadastroLivro;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Larissa
 */
public class FrameInicial extends javax.swing.JFrame {

    /**
     * Creates new form FrameInicial
     */
    public FrameInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btSair = new javax.swing.JButton();
        btCadlivro = new javax.swing.JButton();
        btConsultar = new javax.swing.JButton();
        btCadusuario = new javax.swing.JButton();
        lblivro = new javax.swing.JLabel();
        lbImagem = new javax.swing.JLabel();
        lbBemvindo = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        MenuCadastrar = new javax.swing.JMenu();
        cadLivro = new javax.swing.JMenuItem();
        cadProfessor = new javax.swing.JMenuItem();
        cadAluno = new javax.swing.JMenuItem();
        MenuEditar = new javax.swing.JMenu();
        ediLivro = new javax.swing.JMenuItem();
        ediProfessor = new javax.swing.JMenuItem();
        ediAluno = new javax.swing.JMenuItem();
        MenuExcluir = new javax.swing.JMenu();
        excLivro = new javax.swing.JMenuItem();
        excProfessor = new javax.swing.JMenuItem();
        excAluno = new javax.swing.JMenuItem();
        MenuRelatorios = new javax.swing.JMenu();
        relAlunosclivros = new javax.swing.JRadioButtonMenuItem();
        relProfessoresclivros = new javax.swing.JCheckBoxMenuItem();
        relLivrosnoacervo = new javax.swing.JCheckBoxMenuItem();
        relDevedores = new javax.swing.JCheckBoxMenuItem();
        relTodosusuarios = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 204));

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        btSair.setBackground(new java.awt.Color(253, 253, 211));
        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        btCadlivro.setBackground(new java.awt.Color(255, 255, 153));
        btCadlivro.setForeground(new java.awt.Color(102, 0, 0));
        btCadlivro.setText("Cadastrar Livro");
        btCadlivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadlivroActionPerformed(evt);
            }
        });

        btConsultar.setBackground(new java.awt.Color(255, 255, 153));
        btConsultar.setForeground(new java.awt.Color(102, 0, 0));
        btConsultar.setText("Consultar");
        btConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarActionPerformed(evt);
            }
        });

        btCadusuario.setBackground(new java.awt.Color(255, 255, 153));
        btCadusuario.setForeground(new java.awt.Color(102, 0, 0));
        btCadusuario.setText("Cadastrar Usuario");
        btCadusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadusuarioActionPerformed(evt);
            }
        });

        lbImagem.setIcon(new javax.swing.ImageIcon("C:\\Users\\Larissa\\Downloads\\unrestricted___stacks_of_books_renders_by_frozenstocks-d7n0dq4.png")); // NOI18N
        lbImagem.setText("jLabel1");

        lbBemvindo.setText("Bem vindo, para continuar selecione uma das opções do menu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbImagem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btCadlivro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btCadusuario))
                            .addComponent(lbBemvindo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btConsultar)
                                .addGap(26, 26, 26)
                                .addComponent(lblivro)
                                .addGap(165, 165, 165))
                            .addComponent(btSair, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSair)
                    .addComponent(lbBemvindo))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCadlivro)
                    .addComponent(btCadusuario)
                    .addComponent(btConsultar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblivro, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(524, 524, 524))
        );

        MenuCadastrar.setText("Cadastrar");

        cadLivro.setText("Livro");
        MenuCadastrar.add(cadLivro);

        cadProfessor.setText("Professor");
        MenuCadastrar.add(cadProfessor);

        cadAluno.setText("Aluno");
        MenuCadastrar.add(cadAluno);

        Menu.add(MenuCadastrar);

        MenuEditar.setText("Editar");

        ediLivro.setText("Livro");
        MenuEditar.add(ediLivro);

        ediProfessor.setText("Professor");
        MenuEditar.add(ediProfessor);

        ediAluno.setText("Aluno");
        ediAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ediAlunoActionPerformed(evt);
            }
        });
        MenuEditar.add(ediAluno);

        Menu.add(MenuEditar);

        MenuExcluir.setText("Excluir");

        excLivro.setText("Livro");
        MenuExcluir.add(excLivro);

        excProfessor.setText("Professor");
        MenuExcluir.add(excProfessor);

        excAluno.setText("Aluno");
        MenuExcluir.add(excAluno);

        Menu.add(MenuExcluir);

        MenuRelatorios.setText("Relatórios");

        relAlunosclivros.setSelected(true);
        relAlunosclivros.setText("Alunos com livros");
        MenuRelatorios.add(relAlunosclivros);

        relProfessoresclivros.setSelected(true);
        relProfessoresclivros.setText("Professores com livros");
        MenuRelatorios.add(relProfessoresclivros);

        relLivrosnoacervo.setSelected(true);
        relLivrosnoacervo.setText("Livros no acervo");
        MenuRelatorios.add(relLivrosnoacervo);

        relDevedores.setSelected(true);
        relDevedores.setText("Devedores");
        relDevedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relDevedoresActionPerformed(evt);
            }
        });
        MenuRelatorios.add(relDevedores);

        relTodosusuarios.setSelected(true);
        relTodosusuarios.setText("Todos os usuários ");
        MenuRelatorios.add(relTodosusuarios);

        Menu.add(MenuRelatorios);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
         System.exit(0);
    }//GEN-LAST:event_btSairActionPerformed

    private void btCadlivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadlivroActionPerformed
        FrameInicial.this.dispose();
        FrameCadastroLivro cadastro = new FrameCadastroLivro();
        cadastro.setVisible(true);
    }//GEN-LAST:event_btCadlivroActionPerformed

    private void btCadusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadusuarioActionPerformed
        FrameInicial.this.dispose();
        FrameCadastroPessoas pessoas = new FrameCadastroPessoas();
        pessoas.setVisible(true);
    }//GEN-LAST:event_btCadusuarioActionPerformed

    private void btConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarActionPerformed
        FrameInicial.this.dispose();
        FrameConsulta consulta = new FrameConsulta();
        consulta.setVisible(true);
    }//GEN-LAST:event_btConsultarActionPerformed

    private void relDevedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relDevedoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_relDevedoresActionPerformed

    private void ediAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ediAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ediAlunoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenu MenuCadastrar;
    private javax.swing.JMenu MenuEditar;
    private javax.swing.JMenu MenuExcluir;
    private javax.swing.JMenu MenuRelatorios;
    private javax.swing.JButton btCadlivro;
    private javax.swing.JButton btCadusuario;
    private javax.swing.JButton btConsultar;
    private javax.swing.JButton btSair;
    private javax.swing.JMenuItem cadAluno;
    private javax.swing.JMenuItem cadLivro;
    private javax.swing.JMenuItem cadProfessor;
    private javax.swing.JMenuItem ediAluno;
    private javax.swing.JMenuItem ediLivro;
    private javax.swing.JMenuItem ediProfessor;
    private javax.swing.JMenuItem excAluno;
    private javax.swing.JMenuItem excLivro;
    private javax.swing.JMenuItem excProfessor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbBemvindo;
    private javax.swing.JLabel lbImagem;
    private javax.swing.JLabel lblivro;
    private javax.swing.JRadioButtonMenuItem relAlunosclivros;
    private javax.swing.JCheckBoxMenuItem relDevedores;
    private javax.swing.JCheckBoxMenuItem relLivrosnoacervo;
    private javax.swing.JCheckBoxMenuItem relProfessoresclivros;
    private javax.swing.JRadioButtonMenuItem relTodosusuarios;
    // End of variables declaration//GEN-END:variables
}
