package pacoteFrames;


import pacoteBD.AcessoBD;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Larissa
 */
public class FrameCadastroPessoas extends javax.swing.JFrame {
        
    Pessoa pessoa = new Pessoa();
    Biblioteca biblioteca = new Biblioteca();
        AcessoBD aBD = new AcessoBD();
    /**
     * Creates new form FrameCadastroPessoas
     */
    public FrameCadastroPessoas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgpCategoria = new javax.swing.ButtonGroup();
        painelBemVindo2 = new javax.swing.JPanel();
        painelCadastroPessoas = new javax.swing.JPanel();
        lbNome = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        lbRg = new javax.swing.JLabel();
        ftfRg = new javax.swing.JFormattedTextField();
        lbCpf = new javax.swing.JLabel();
        ftfCpf = new javax.swing.JFormattedTextField();
        lbCategoria = new javax.swing.JLabel();
        rbProfessor = new javax.swing.JRadioButton();
        rbAluno = new javax.swing.JRadioButton();
        lbBemVindo1 = new javax.swing.JLabel();
        painelBotoes2 = new javax.swing.JPanel();
        btCadastrar = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btBuscar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btVoltar = new javax.swing.JButton();
        lbSnoopy = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 204));

        painelBemVindo2.setBackground(new java.awt.Color(255, 255, 204));
        painelBemVindo2.setForeground(new java.awt.Color(255, 255, 204));

        painelCadastroPessoas.setBackground(new java.awt.Color(255, 255, 204));

        lbNome.setForeground(new java.awt.Color(51, 0, 0));
        lbNome.setText("Nome:");

        tfNome.setForeground(new java.awt.Color(51, 0, 0));
        tfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeActionPerformed(evt);
            }
        });
        tfNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfNomeKeyTyped(evt);
            }
        });

        lbRg.setForeground(new java.awt.Color(51, 0, 0));
        lbRg.setText("RG:");

        ftfRg.setForeground(new java.awt.Color(51, 0, 0));
        ftfRg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftfRgActionPerformed(evt);
            }
        });

        lbCpf.setForeground(new java.awt.Color(51, 0, 0));
        lbCpf.setText("CPF:");

        ftfCpf.setForeground(new java.awt.Color(51, 0, 0));

        lbCategoria.setForeground(new java.awt.Color(51, 0, 0));
        lbCategoria.setText("Categoria:");

        rbProfessor.setBackground(new java.awt.Color(255, 255, 204));
        btgpCategoria.add(rbProfessor);
        rbProfessor.setForeground(new java.awt.Color(51, 0, 0));
        rbProfessor.setText("Professor");
        rbProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbProfessorActionPerformed(evt);
            }
        });

        rbAluno.setBackground(new java.awt.Color(255, 255, 204));
        btgpCategoria.add(rbAluno);
        rbAluno.setForeground(new java.awt.Color(51, 0, 0));
        rbAluno.setText("Aluno");

        lbBemVindo1.setForeground(new java.awt.Color(102, 0, 0));
        lbBemVindo1.setText("Bem vindo ao sistema de Cadastro de Pessoas! Para começar preencha os campos a seguir:");

        javax.swing.GroupLayout painelCadastroPessoasLayout = new javax.swing.GroupLayout(painelCadastroPessoas);
        painelCadastroPessoas.setLayout(painelCadastroPessoasLayout);
        painelCadastroPessoasLayout.setHorizontalGroup(
            painelCadastroPessoasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCadastroPessoasLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(painelCadastroPessoasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbBemVindo1)
                    .addGroup(painelCadastroPessoasLayout.createSequentialGroup()
                        .addComponent(lbNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelCadastroPessoasLayout.createSequentialGroup()
                        .addComponent(lbRg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ftfRg, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbCpf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ftfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelCadastroPessoasLayout.createSequentialGroup()
                        .addComponent(lbCategoria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbProfessor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbAluno)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        painelCadastroPessoasLayout.setVerticalGroup(
            painelCadastroPessoasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCadastroPessoasLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbBemVindo1)
                .addGap(27, 27, 27)
                .addGroup(painelCadastroPessoasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNome)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelCadastroPessoasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRg)
                    .addComponent(ftfRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCpf)
                    .addComponent(ftfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelCadastroPessoasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCategoria)
                    .addComponent(rbProfessor)
                    .addComponent(rbAluno))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        painelBotoes2.setBackground(new java.awt.Color(255, 255, 204));

        btCadastrar.setBackground(new java.awt.Color(255, 255, 153));
        btCadastrar.setForeground(new java.awt.Color(102, 0, 0));
        btCadastrar.setText("Cadastrar");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        btAlterar.setBackground(new java.awt.Color(255, 255, 153));
        btAlterar.setForeground(new java.awt.Color(102, 0, 0));
        btAlterar.setText("Alterar");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        btBuscar.setBackground(new java.awt.Color(255, 255, 153));
        btBuscar.setForeground(new java.awt.Color(102, 0, 0));
        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        btExcluir.setBackground(new java.awt.Color(255, 255, 153));
        btExcluir.setForeground(new java.awt.Color(102, 0, 0));
        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btSair.setBackground(new java.awt.Color(253, 253, 212));
        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        btLimpar.setBackground(new java.awt.Color(253, 253, 212));
        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btVoltar.setBackground(new java.awt.Color(255, 153, 102));
        btVoltar.setForeground(new java.awt.Color(102, 51, 0));
        btVoltar.setText("Voltar");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelBotoes2Layout = new javax.swing.GroupLayout(painelBotoes2);
        painelBotoes2.setLayout(painelBotoes2Layout);
        painelBotoes2Layout.setHorizontalGroup(
            painelBotoes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBotoes2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btExcluir)
                .addGap(33, 33, 33)
                .addComponent(btSair)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btLimpar)
                .addGap(25, 25, 25)
                .addComponent(btVoltar)
                .addContainerGap(217, Short.MAX_VALUE))
        );
        painelBotoes2Layout.setVerticalGroup(
            painelBotoes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBotoes2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelBotoes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCadastrar)
                    .addComponent(btAlterar)
                    .addComponent(btBuscar)
                    .addComponent(btExcluir)
                    .addComponent(btSair)
                    .addComponent(btLimpar)
                    .addComponent(btVoltar))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout painelBemVindo2Layout = new javax.swing.GroupLayout(painelBemVindo2);
        painelBemVindo2.setLayout(painelBemVindo2Layout);
        painelBemVindo2Layout.setHorizontalGroup(
            painelBemVindo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelBotoes2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(painelBemVindo2Layout.createSequentialGroup()
                .addComponent(painelCadastroPessoas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbSnoopy, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        painelBemVindo2Layout.setVerticalGroup(
            painelBemVindo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBemVindo2Layout.createSequentialGroup()
                .addGroup(painelBemVindo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelBemVindo2Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(lbSnoopy, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBemVindo2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(painelCadastroPessoas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(painelBotoes2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelBemVindo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelBemVindo2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ftfRgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftfRgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftfRgActionPerformed

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        
        
        pessoa.setNome(tfNome.getText());
        pessoa.setCpf(ftfCpf.getText());
        pessoa.setRg(ftfRg.getText());
        pessoa.setCategoria(rbProfessor.isSelected() ? "Professor" : "Aluno");
        
        
        
        try {
            aBD.inserirNovaPessoa(pessoa);
        } catch (SQLException ex) {
            Logger.getLogger(FrameCadastroPessoas.class.getName()).log(Level.SEVERE, null, ex);
        }
        btLimparActionPerformed(null);
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        
         ResultSet rs;
         int numLinhas = 0;
         String cpf;
              
         
         cpf = ftfCpf.getText();
         
         
         try{
         rs = aBD.buscarPessoaCPF(cpf);
         
         while (rs.next()){
                
                ftfCpf.setText(rs.getString("CPF"));
                ftfRg.setText(rs.getString("RG"));
                tfNome.setText(rs.getString("NOME"));
                rbProfessor.setText(rs.getString("CATEGORIA"));
                rbAluno.setText(rs.getString("CATEGORIA"));
                
         numLinhas ++;   
         }
         
         }catch (SQLException ex){
             Logger.getLogger(FrameCadastroPessoas.class.getName()).log(Level.SEVERE, null, ex);
                 }
         
    }//GEN-LAST:event_btBuscarActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        String cpfPessoa;
        
        Pessoa pessoa = new Pessoa();
        
        cpfPessoa = ftfCpf.getText();  
        
               pessoa = new Pessoa(
               ftfCpf.getText(),
               ftfRg.getText(),
               tfNome.getText(),
               (rbProfessor.isSelected()== true?"Professor":"Aluno").toString());
                  
        
        try {
            aBD.alterarPessoaCPF(cpfPessoa, pessoa);
            
        } catch (SQLException ex) {
            Logger.getLogger(FrameCadastroPessoas.class.getName()).log(Level.SEVERE, null, ex);
        
    }   
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
       String cpfPessoa;
        
        
        cpfPessoa = ftfCpf.getText();  
                  
        
        try {
            aBD.excluirPessoaCPF(cpfPessoa);
            
           
        } catch (SQLException ex) {
            Logger.getLogger(FrameCadastroPessoas.class.getName()).log(Level.SEVERE, null, ex);
    }//GEN-LAST:event_btExcluirActionPerformed
    LimparCampos();
    }
    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed

        LimparCampos();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btSairActionPerformed

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
          FrameCadastroPessoas.this.dispose();
        FrameInicial inicial = new FrameInicial();
        inicial.setVisible(true);
        
    }//GEN-LAST:event_btVoltarActionPerformed

   
    private void rbProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbProfessorActionPerformed

    private void tfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeActionPerformed

    private void tfNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNomeKeyTyped
          char car = evt.getKeyChar();    
          if((car<'a' || car>'z') && (car<'A' || car>'Z') 
          && car !='á'  && car !='é' && car !='í'  && car !='ó'  && car !='ú' 
                  && car !='Á'              && car !='É'               && car !='Í'              
                  && car !='Ó'    && car !='Ú'    && car !='ñ'    && car !='Ñ'        
                  && (car!=(char)KeyEvent.VK_SPACE)){       evt.consume();  }
    }//GEN-LAST:event_tfNomeKeyTyped
 public void LimparCampos(){
     ftfCpf.setText("");
        ftfRg.setText("");
        tfNome.setText("");
        btgpCategoria.clearSelection();
 }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameCadastroPessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameCadastroPessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameCadastroPessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameCadastroPessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameCadastroPessoas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSair;
    private javax.swing.JButton btVoltar;
    private javax.swing.ButtonGroup btgpCategoria;
    private javax.swing.JFormattedTextField ftfCpf;
    private javax.swing.JFormattedTextField ftfRg;
    private javax.swing.JLabel lbBemVindo1;
    private javax.swing.JLabel lbCategoria;
    private javax.swing.JLabel lbCpf;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbRg;
    private javax.swing.JLabel lbSnoopy;
    private javax.swing.JPanel painelBemVindo2;
    private javax.swing.JPanel painelBotoes2;
    private javax.swing.JPanel painelCadastroPessoas;
    private javax.swing.JRadioButton rbAluno;
    private javax.swing.JRadioButton rbProfessor;
    private javax.swing.JTextField tfNome;
    // End of variables declaration//GEN-END:variables
}
